### ISSUE TITLE
Short Id

### ISSUE THREAD

**Issue by so0k** [cloudposse/terraform-null-label#10]
How to handle short Id's for resources such as ElastiCache clusters which have the following constraints:

>Cluster naming constraints
>
>Must contain from 1 to 20 alphanumeric characters or hyphens.
>Must begin with a letter.
>Cannot contain two consecutive hyphens.
>Cannot end with a hyphen.

**Comment by so0k** [comment]
can add 3 variables:

```hcl
variable short_stage_lookup {
  default = {
    staging = "stg"
    prod    = "prd"
    dev     = "dev"
  }
}

variable "short_namespace" {
  type        = "string"
  description = "Defaults to the first 2 characters of the namespace"
  default     = ""
}

variable "short_stage" {
  type        = "string"
  description = "Tries to lookup a 3 character acronym or falls back to the first 3 characters of the stage"
  default     = ""
}

variable "short_name" {
  type        = "string"
  description = "Defaults to the first 3 characters of the name (max 14 to stay below 20 characters)"
  default     = ""
}
```

and add something like this:
```hcl
locals {
  short_namespace = "${var.short_namespace == "" ? substr(var.namespace,0,2) : var.short_namespace}"
  short_stage     = "${var.short_stage == "" ? lookup(var.short_stage_lookup,lower(var.stage),substr(var.stage,0,3)) : var.short_stage}"
  short_name      = "${var.short_name == "" ? substr(var.name,0,3) : var.short_name}"
}
resource "null_resource" "default" {
  triggers = {
    ...
    short_id   = "${lower(join(var.delimiter, list(local.short_namespace, local.short_stage, local.short_name)))}"
    ...
  }
}
```

for an example configuration of:
```hcl
module "label" {
  source          = "../"
  namespace       = "honestbee"
  short_namespace = "hb"
  stage           = "Staging"
  name            = "Name"
  attributes      = ["1", "2", "3", ""]
  tags            = "${map("Key", "Value")}"
}
```

you get
```
+ module.label.null_resource.default
      id:                  <computed>
      triggers.%:          "6"
      triggers.attributes: "1-2-3"
      triggers.id:         "honestbee-staging-name-1-2-3"
      triggers.name:       "name"
      triggers.namespace:  "honestbee"
      triggers.short_id:   "hb-stg-nam"
      triggers.stage:      "staging"
```

it drops attributes, so it doesn't guarantee full uniqueness...

**Comment by osterman** [comment]
First of all, @so0k thanks for taking the time to put together such a thorough request!

Let me help understand your problem better. Why not just define two instances of the module? One for short labels, one for long labels? 

E.g.
```
module "short_label" {
  source          = "../"
  namespace  = "hb"
  stage            = "stg"
  name            = "vln"
}
```

```
module "long_label" {
  source          = "../"
  namespace  = "honestbee"
  stage            = "Staging"
  name            = "VeryLongName"
}
```

Then use the labels as needed?

Fwiw, our published "best practice" is to err on the side of caution and opt for shorter labels across the board. It only adds to confusion to have 2 sets of labels - "long"  and "short".

Regarding "Cluster naming constraints", nothing in the existing module precludes that usage.

> Must contain from 1 to 20 alphanumeric characters or hyphens.
> Must begin with a letter.
> Cannot contain two consecutive hyphens.
> Cannot end with a hyphen.

The module does not violate any of these naming constraints. The user might. Even using "short" names combined with `attributes` can cause an overflow, thus the only scalable approach is to put the onus on the caller of the module to use names that scale.

That said, I think we could update our documentation to call out this use-case as to why short names/abbreviations should be used.

What if there was a new label module that implemented both long & short names by instantiating this module twice? One for `short` and one for `long`? Just a thought....


@aknysh, @comeanother, @goruha - any thoughts?

**Comment by osterman** [comment]
The other consideration is how this works when combined with lots of modules. For example, since we leverage the label module in essentially all modules, it would be a real burden to pass 2x the number of parameters for each module instantiation.

https://github.com/cloudposse/terraform-aws-elastic-beanstalk-environment/blob/master/main.tf#L923

**Comment by so0k** [comment]
Thank you for some great suggestions on how to approach the problem in different ways.

From my perspective, I wanted to use the same label for multiple resources, and some have very restricted rules for their `identity` - but I still want the long name in the tags (for AWS resource Groups). 

I could create a composed labelling module, or create 2 instances as well. For now, I added the parameters for `short_id` for an internal project, the defaults do not require me to pass in all attributes twice, and it works for my use case at the moment.

**Comment by osterman** [comment]
Thanks again! Going to close this for now.
