### ISSUE TITLE
Change order of attribute concatination

### ISSUE THREAD

**Issue by Nuru** [cloudposse/terraform-null-label#113]
When null-label was converted to the `context.tf` format, the `context` attributes were put after the `var` attributes. 
https://github.com/cloudposse/terraform-null-label/blob/3861091c159d77115703b43cb88a47f6ee6a6191/main.tf#L30

This turns out to be not what we want in all the modules I have reviewed so far. Modules always want to put their attributes at the end of the list. Right now they do this with code like this:

```hcl
module "label" {
  source  = "cloudposse/label/null"
  version = "0.22.0"

  attributes = compact(concat(var.attributes, ["workers"]))
  tags       = local.tags

  context = module.this.context
}
```

If null-label put the `var.attributes` last, like this:

```
 attributes  = compact(distinct(concat(var.context.attributes, var.attributes))) 
```

then modules would be simplified:

```hcl
module "label" {
  source  = "cloudposse/label/null"
  version = "0.22.0"

  attributes = ["workers"]
  tags       = local.tags

  context = module.this.context
}
```

**Comment by dknell** [comment]
this is causing terraform to want to replace a LOT of my resources. I cannot run any of my terraform right now.

```
      ~ name                   = "dt-prod-api-ecs-service" -> "dt-prod-api-service-ecs" # forces replacement
```

**Comment by if-igor** [comment]
Just in the middle of upgrading my modules, and I am seeing a large number of resource destroy/creates due to the attribute order change. This will cause backward compatibility problems either way, I guess, but it would be great to have the ability to control the order (via a local attributes value, for instance) with a module input variable.

**Comment by Nuru** [comment]
@if-igor Look for a fix soon

**Comment by if-igor** [comment]
@Nuru Thank you!
