### ISSUE TITLE
Unsupported Core Version 0.14.2

### ISSUE THREAD

**Issue by sfc-gh-pkommini** [cloudposse/terraform-null-label#115]
Found a bug? Maybe our [Slack Community](https://slack.cloudposse.com) can help. 

[![Slack Community](https://slack.cloudposse.com/badge.svg)](https://slack.cloudposse.com)

## Describe the Bug
```bash
Initializing modules...

Error: Unsupported Terraform Core version

  on .terraform/modules/ec2-bastion-server.dns.this/versions.tf line 2, in terraform:
   2:   required_version = ">= 0.12.0, < 0.14.0"

Module module.ec2-bastion-server.module.dns.module.this (from
git::https://github.com/cloudposse/terraform-null-label.git?ref=tags/0.19.2)
does not support Terraform version 0.14.2. To proceed, either choose another
supported Terraform version or update this version constraint. Version
constraints are normally set for good reason, so updating the constraint may
lead to other errors or unexpected behavior.
```

## Expected Behavior
I expected the `terraform init` to setup the ec2-bastion-server module successfully.

## Steps to Reproduce
1. Use terraform 0.14.2
2. Use the cloudposse/ec2-bastion-server module
3. Perform `terraform init`

## Screenshots
```
Initializing modules...

Error: Unsupported Terraform Core version

  on .terraform/modules/ec2-bastion-server.dns.this/versions.tf line 2, in terraform:
   2:   required_version = ">= 0.12.0, < 0.14.0"

Module module.ec2-bastion-server.module.dns.module.this (from
git::https://github.com/cloudposse/terraform-null-label.git?ref=tags/0.19.2)
does not support Terraform version 0.14.2. To proceed, either choose another
supported Terraform version or update this version constraint. Version
constraints are normally set for good reason, so updating the constraint may
lead to other errors or unexpected behavior.
```

## Environment (please complete the following information):

Anything that will help us triage the bug will help. Here are some ideas:
 - OS: MacOS
 - Version 10.15.7

**Comment by osterman** [comment]
This module is compatible with 0.14. The downstream module probably needs to be updated to use a newer version of this module.

**Comment by osterman** [comment]
https://github.com/cloudposse/terraform-null-label/blob/master/versions.tf#L2

**Comment by sfc-gh-pkommini** [comment]
Makes sense. I've pushed a PR to update the ec2-bastion-server module. Thank you. :)
