### ISSUE TITLE
Document Usage of Stage Parameter

### ISSUE THREAD

**Issue by osterman** [cloudposse/terraform-null-label#29]
## what
* Document usage of `stage` parameter 
* Explain why the term `stage` is used rather than environment

## why
* Users may not be accustomed to the nomenclature due to commonly misused usage of the term `stage`

## references

>  can you give me some idea why the term 'stage' was chosen over 'environment'? In the label module?

A "stage" is where software performs (e.g. runs). The term `environment` is also overloaded and often abbreviated as env,  which from my subjective experience more confusing. Stage IMO is misused inside many organizations. We made it our personal mission to correct its usage, however, I could maybe consider adding environment after stage as another (optional) dimension of disambiguation.

![image](https://user-images.githubusercontent.com/52489/43100789-3d549814-8e7b-11e8-8c41-7f4038bf682d.png)
![image](https://user-images.githubusercontent.com/52489/43100794-4294e61c-8e7b-11e8-9099-924017d53cf7.png)

that is to say, "staging is a stage", but a stage is not always staging.

>  what's the name for the env between dev and prod?

that might be staging. note, that staging is not the same word as stage. other options are "QA", "UAT" or "Preproduction".

<https://en.wikipedia.org/wiki/Multistage_rocket>

**Comment by Nuru** [comment]
@osterman I am closing this now that we have both `environment` and `stage` for people to choose from.
