### ISSUE TITLE
Make it possible to have different naming sequences

### ISSUE THREAD

**Issue by huksley** [cloudposse/terraform-null-label#35]
Currently, this repo supports only `namespace-stage-name` sequence.
In some organizations, there is a different standard for example `namespace-name-stage`.

Please consider and explore whether it is possible to support different naming sequences.

**Comment by huksley** [comment]
To clarify I am using label through following projects (not directly):

https://github.com/cloudposse/terraform-aws-cicd
https://github.com/cloudposse/terraform-aws-codebuild

**Comment by aknysh** [comment]
Addressed in https://github.com/cloudposse/terraform-null-label/pull/36
