### ISSUE TITLE
regex_replace_chars does not behave as expected

### ISSUE THREAD

**Issue by henrydobson** [cloudposse/terraform-null-label#49]
regex_replace_chars conversion to a variable has been implemented as a string. See https://github.com/cloudposse/terraform-null-label/blob/master/main.tf#L30

This causes the desired regex replacements on the input strings to fail.

Incorrect
```hcl
  name = "${lower(replace(local.name_or_context, "/var.regex_replace_chars/", ""))}"
```  

Correct
```hcl
  name = "${lower(replace(local.name_or_context, "/${var.regex_replace_chars}/", ""))}"
```

I expect the `module.labels.id` output of the following module configuration to be `null-dev-activedirectory`.

The actual output is `null-dev-active-directory`

```hcl
module "labels" {
  source     = "git::https://github.com/cloudposse/terraform-null-label.git?ref=master"
  namespace  = "${var.namespace}" # null
  stage      = "${var.stage}" # dev
  name       = "${var.name}" # var.name = "active-directory"
  attributes = "${var.attributes}"
  delimiter  = "-"

  tags = "${merge(
    map("ShutDownPolicy", "uk-office-hours"),
    map("GitSha", "${var.revision_id}"),
    map("BranchName", "${var.branch_name}"),
    map("App", "${var.component_name}"),
    var.tags)}"
}
```

**Comment by r-divakaran** [comment]
I am setting the `regex_replace_chars` to be `^[a-zA-Z0-9!@#$&()\\-`.+,/\"]*$` so that it allows all special characters. But after this change, its again removing hyphens!

May be I am using the wrong regex can some one please help. Thanks!

**Comment by aknysh** [comment]
@r-divakaran  can you try the latest release https://github.com/cloudposse/terraform-null-label/releases/tag/0.6.2 and see if are you still having the issue.
Ping us here with the result.

**Comment by osterman** [comment]
@r-divakaran make sure you wrap your regex in slashes to follow the terraform syntax for regexes.

**Comment by aknysh** [comment]
@r-divakaran  also, the regex seems to be wrong (with errors).
Take a look here https://regexr.com/  (paste the regex to test it)

**Comment by osterman** [comment]
`^[a-zA-Z0-9!@#$&()\\-.+,/\"]*$` this does not look like what you want as it's anchoring to the beginning and ending of the string using the `^` and `$`.

**Comment by aknysh** [comment]
![image](https://user-images.githubusercontent.com/7356997/52987261-6c012180-33c8-11e9-9251-11191b8ee6e5.png)

**Comment by r-divakaran** [comment]
Thanks for the feedback @aknysh @osterman .

I changed the regex to `"/[^a-zA-Z0-9\\-]/"` and it's still not working. 
So as to test this, I created a file with contents

```
variable "environment" {
  default = "dev-100"
}

variable "search" {
  default = "/[^a-zA-Z0-9\\-]/"
}

output "preserve_hyphen" {
  value = "${replace("var.environment,var.srch,"")}"
}
```

The I execute

```
terraform apply
```

I get an output like
```
Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

preserve_hyphen = dev-100
```

But the same is not working with null_label.

**Comment by aknysh** [comment]
@r-divakaran did you use this regex `/[^a-zA-Z0-9\\-]/`
in the variable

```
variable "regex_replace_chars" {
  type        = "string"
  default     = "/[^a-zA-Z0-9\\-]/"
  description = "Regex to replace chars with empty string in `namespace`, `environment`, `stage` and `name`. By default only letters and digits are allowed, all other chars are removed"
}
```

Did you try using this `/[^a-zA-Z0-9-]/`?

**Comment by r-divakaran** [comment]
Yes @aknysh I had set it to.

Just now I tried it by setting like this
```
variable "regex_replace_chars" {
  type        = "string"
  default     =  "/[^a-zA-Z0-9-]/"
  description  = "By default these special characters are allowed in in name, environment, namespace and stage"
}
```

Still resulting same! :( Thanks

**Comment by r-divakaran** [comment]
It would be really great if one of you can try recreate the issue am facing. I'd like to switch from using my own fork to the master branch of of this module.
Main thing is that, I need to have a hyphen in my environment name and to achieve that what should be the value for `regex_replace_chars` ? Thank you

**Comment by aknysh** [comment]
@r-divakaran 
I just tested the module with the following regex:

```
regex_replace_chars = "/[^a-zA-Z0-9-]/"
```

and it's working, the hyphen is not removed from the name.

This also works:

```
regex_replace_chars = "/[^a-zA-Z0-9\\-]/"
```

Will close the issue for now, please reopen if you are still having problems.

**Comment by aknysh** [comment]
Here is he example I tested:

```
module "label1" {
  source      = "../../"
  namespace   = "CloudPosse"
  environment = "UAT"
  stage       = "build"
  name        = "Winston---Churchroom7"
  attributes  = ["fire", "water", "earth", "air"]
  delimiter   = "-"

  label_order = ["name", "environment", "stage", "attributes"]

  tags = {
    "City"        = "Dublin"
    "Environment" = "Private"
  }

  regex_replace_chars = "/[^a-zA-Z0-9-]/"
}
```

And the output:

```
label1 = {
  attributes = [fire water earth air]
  id = winston---churchroom7-uat-build-fire-water-earth-air
  name = winston---churchroom7
  namespace = cloudposse
  stage = build
}
label1_context = {
  attributes = [fire water earth air]
  delimiter = [-]
  environment = [uat]
  label_order = [name environment stage attributes]
  name = [winston---churchroom7]
  namespace = [cloudposse]
  stage = [build]
  tags_keys = [City Environment Name Namespace Stage]
  tags_values = [Dublin Private winston---churchroom7-uat-build-fire-water-earth-air cloudposse build]
}
label1_tags = {
  City = Dublin
  Environment = Private
  Name = winston---churchroom7-uat-build-fire-water-earth-air
  Namespace = cloudposse
  Stage = build
}
```

**Comment by r-divakaran** [comment]
Thanks a lot for verifying this and also putting hyphen in the default value. I was able to get it working.

The silliest mistake, that was happening for me was that.. terraform was using the local cached module! :( Sorry!
