### ISSUE TITLE
provider null_resource not found

### ISSUE THREAD

**Issue by namcxn** [cloudposse/terraform-null-label#62]
Hello,

I get error:
> Provider "null_resource" not available for installation.
> 
> A provider named "null_resource" could not be found in the official repository.
> 
> This may result from mistyping the provider name, or the given provider may
> be a third-party provider that cannot be installed automatically.
> 
> In the latter case, the plugin must be installed manually by locating and
> downloading a suitable distribution package and placing the plugin's executable
> file in the following directory:
>     terraform.d/plugins/darwin_amd64
> 
> Terraform detects necessary plugins by inspecting the configuration and state.
> To view the provider versions requested by each module, run
> "terraform providers".

I check in official reposistory of terraform not proviver `null_resource`, only provider `null`
link ref: https://www.terraform.io/docs/providers/null/index.html

**Comment by osterman** [comment]
Sorry, master was temporarily unstable. See recent pull requests. This has been resolved and fixed in our tests. Also, as a word of caution, never pin to master. What is “stable” in master might not be stable in your environment.
