### ISSUE TITLE
Name tags should have value of local.id

### ISSUE THREAD

**Issue by thoregilk** [cloudposse/terraform-null-label#66]
If I am not mistaken, previously the name tag where equal to local.id but now it seems that it is been set to local.name

**Comment by osterman** [comment]
Yikes, that might be the case. I will have a look in the morning.

**Comment by thoregilk** [comment]
Great, we`ve gone around it in a local branch by implementing a tag_context that references name to local.id and removes the attributes from tags as that where either not present before. 

``` 
generated_tags = { for l in keys(local.tag_context) : title(l) => local.tag_context[l] if length(local.tag_context[l]) > 0 }


tag_context = {
    name        = local.id
    namespace   = local.namespace
    environment = local.environment
    stage       = local.stage
}
