### ISSUE TITLE
Ability to Have Required Tags

### ISSUE THREAD

**Issue by anthonycolon25** [cloudposse/terraform-null-label#74]
Hi,

This is more of a question.  Is there a way to enforce required tags while also providing the ability to add additional tags as needed. 

For example, if I have BusinessUnit and CostCenter that every resource must have and "ManagedBy" is an ad-hoc tag that they want to add.

Could this be possible by creating a module (which has the required variables) that calls your module? Basically a pass-thru except it would create a joint tags map (required and ad-hoc) and pass that to your module.

Any ideas?

**Comment by osterman** [comment]
I can see the use-case, but unfortunately no way to enforce it in this module. Ideally, you'd create a new module for your organization that defines `business_unit` and `cost_center` as variables in terraform with no default values. That way you can enforce that they are passed. Your module could then call `cloudposse/terraform-null-label` and pass those settings as tags.

**Comment by Nuru** [comment]
I agree with @osterman and am closing this issue as `wontfix`. To the extent this feature is valuable, it should be supported by an upstream module, not this one.
