### ISSUE TITLE
Empty delimiter does not work with TF 0.12

### ISSUE THREAD

**Issue by jhosteny** [cloudposse/terraform-null-label#77]
The delimiter is calculated with the `coalesce` function, which considers and empty string and a null string as the same thing. This prevents the delimiter from being set as "", which is useful for certain resources. For example, Azure storage account container names can only contain lowercase letters and numbers.

I'm not sure of the best way to fix this, other than add a flag that says to not use the delimiter. The regex is applied before the delimiter is added. I could submit a PR for a new flag if that would be acceptable.

**Comment by tyler-iherb** [comment]
i cant remove delimiter, please add this option to not use

**Comment by osterman** [comment]
Hrmm... sure, if you want to submit a PR for this, we'll accept it.
