### ISSUE TITLE
enabled input not working

### ISSUE THREAD

**Issue by phu-b4r** [cloudposse/terraform-null-label#78]
I'm trying to implement tagging based on the environment, and one of the way I trying is by conditionally setting the 'enabled' string. e.g.

module "dev_label" {
  enabled   = "${var.env == "dev" ? true : false}"
  source     = "git::https://github.com/cloudposse/terraform-null-label.git?ref=0.11.1"
  name       =  "test"

  tags = {
    "Dev" = "true",
    "Snapshot"     = "true"
  }
}

But this doesn't seem to work, I even just set 'enable = false' to test the feature but that doesn't work either. What am I doing wrong or is this a bug?

I'm using terraform 0.11 hence using the 0.11.1 release. 

Thanks,
Phu

**Comment by osterman** [comment]
Since this is related to terraform 0.11, going to close this issue.
