### ISSUE TITLE
variables are not properly formatted

### ISSUE THREAD

**Issue by ajithreddygeth** [cloudposse/terraform-null-label#83]
in main.tf and all terraform files the variables are not properly formatted. Terraform throws error if i use    `name = var.name` it should be   `name = "${var.name}"`

**Comment by aknysh** [comment]
@ajithreddygeth 
the module was converted to TF 0.12, and `name = var.name` is the correct TF 0.12 syntax.

`name = "${var.name}"` is TF 0.11 syntax.
If you use TF 0.11, use releases `0.11.1` or older 
https://github.com/cloudposse/terraform-null-label/releases/tag/0.11.1
