### ISSUE TITLE
Meaning of Namespace

### ISSUE THREAD

**Issue by BarnumD** [cloudposse/terraform-null-label#87]
What is the intended meaning of the term 'namespace' in this context?  Is it just an arbitrary name, like company name, or client name (anything you want?)

**Comment by aknysh** [comment]
@BarnumD 
`namespace` is like namespace in other languages (C#, Java) - to organize the code and establish unique and consistent naming convention.
It could be your company name, your company abbreviation, or anything you like that is meaningful to you. 
For example, in your company you could use:
namespace = mycompany
stage = prod, staging, dev, testing
name = myapp

then the label module will generate resources' IDs like these:
mycompany-dev-myapp
mycompany-prod-myapp
mycompany-staging-myapp
mycompany-testing-myapp

It's useful by itself to be unique and consistent across companies, environment, etc, but especially when you create IDs for global resources like S3 buckets.

Keep it short, some AWS resources do not accept names/IDs longer than 32 chars.

Examples:
https://github.com/cloudposse/terraform-aws-eks-cluster/blob/master/examples/complete/fixtures.us-east-2.tfvars
https://github.com/cloudposse/testing.cloudposse.co/blob/master/Dockerfile#L9
https://github.com/cloudposse/prod.cloudposse.co/blob/master/Dockerfile#L19

**Comment by BarnumD** [comment]
Thanks.
