### ISSUE TITLE
Make var.label_order "global"

### ISSUE THREAD

**Issue by Mahlstrom** [cloudposse/terraform-null-label#88]
This is not really an issue in this module but in all modules using this module.

I would like to set label_order in a top module ie ecs web app and then all submodules would inherit the label_order.

Our naming convention is not like yours and the only thing that keep me from going from your modules to my own is label_order.

**Comment by osterman** [comment]
Yes, agree - we just haven't had a change to update all the modules with this flag (since we don't personally use it - it was contributed). We'll accept all PRs that add this flag.

**Comment by osterman** [comment]
We're working on a strategy to improve our utilization of all the null label variables across our module by copying a `context.tf` file into every module with the common variables.

**Comment by Nuru** [comment]
Closing as "as fixed as we are going to fix it" by #99 which updates this module and Cloud Posse's architectural pattern to implement this feature, but does require updates to every module in the chain.
