### ISSUE TITLE
Any plans to bump the supported terraform version to v0.12.19

### ISSUE THREAD

**Issue by markmacmahon** [cloudposse/terraform-null-label#91]
Hi, I upgraded terraform to v0.12.19 to work around the forthcoming AWS RDS ssl certification expiration issue documented [here](https://github.com/terraform-providers/terraform-provider-aws/issues/10417).
However this upgrade is no longer compatible with traefic due to the version being pinned at required_version = "~> 0.12.0"  in versions.tf
Are there any plans to support terraform versions >= 0.12.19 ?
Thanks,
Mark

`Initializing modules...

Error: Unsupported Terraform Core version

Module traefik.default_label (from
"git::https://github.com/cloudposse/terraform-null-label.git?ref=tags/0.11.1")
does not support Terraform version 0.12.19. To proceed, either choose another
supported Terraform version or update the module's version constraint. Version
constraints are normally set for good reason, so updating the constraint may
lead to other errors or unexpected behavior.`

**Comment by aknysh** [comment]
@markmacmahon 

required_version = "~> 0.12.0" will support 0.12.19 as well.
It will support everything up to 0.13.
https://devhints.io/semver

https://github.com/cloudposse/terraform-null-label.git?ref=tags/0.11.1 is terraform 0.11 version.
Update to the latest 0.16.0 and try again.

thanks
