### ISSUE TITLE
Ability to set max length of ID output

### ISSUE THREAD

**Issue by tibbing** [cloudposse/terraform-null-label#93]
I'm a heavy user of this module for naming resources, but often find myself writing workarounds for limiting the length of the output ID. Many resources have a max allowed length of the names (such as `aws_lb` and `aws_alb_target_group` (32 characters), `aws_iam_role` (64 characters) etc. 

It would be really nice to have an input parameter `max_id_length` capping the output ID, while still keeping it unique. Suggested implementation:

```
....
variable "max_id_length" {
  type        = number
  default     = 64
  description = "Specify max length of output id result"
}

locals {
  ...
  full_id = lower(join(local.delimiter, local.labels))
  id_hash   = md5(local.full_id)
  id_capped = var.max_id_length <= 6 ? substr(local.id_hash, 0, var.max_id_length) : "${replace(substr(local.full_id, 0, var.max_id_length - 6), "/-$/", "")}-${substr(local.id_hash, 0, 5)}"
  id        = var.max_id_length != 0 && length(local.full_id) > var.max_id_length ? local.id_capped : local.full_id
}
```

I can give it a go and make a PR if you like the idea.

**Comment by osterman** [comment]
@tibbing yes, this has come up quite a bit. We would accept a PR for this functionality.  I like your proposal of offering a few different kinds of outputs. I'd maybe call `id_capped` instead `id_truncated` or `id_short`. Let's call `id_hash` just `id_md5` since there are multiple ways to hash.

**Comment by tibbing** [comment]
@osterman Good points! Please see the referenced PR. I was considering whether to use the given delimiter, or force a dash before the hash, or even skip it altogether. The problem with using the given delimiter is that if the ID happens to be truncated just after a delimiter, we don't want to add another delimiter. Do you have any preference?
